// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.permate.attribution.permate_attribution

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PermateAttributionApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class AttributionOptionsDto (
  val environment: String,
  val baseUrl: String? = null,
  val logLevel: String,
  val sessionEnabled: Boolean,
  val minTimeBetweenSessionsMs: Long,
  /** iOS REQ-SDK-017 — ignored on Android (no-op). */
  val disableAdvertisingIdentifier: Boolean,
  /** iOS REQ-SDK-017 — ignored on Android (no-op). */
  val disableIDFVCollection: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttributionOptionsDto {
      val environment = pigeonVar_list[0] as String
      val baseUrl = pigeonVar_list[1] as String?
      val logLevel = pigeonVar_list[2] as String
      val sessionEnabled = pigeonVar_list[3] as Boolean
      val minTimeBetweenSessionsMs = pigeonVar_list[4] as Long
      val disableAdvertisingIdentifier = pigeonVar_list[5] as Boolean
      val disableIDFVCollection = pigeonVar_list[6] as Boolean
      return AttributionOptionsDto(environment, baseUrl, logLevel, sessionEnabled, minTimeBetweenSessionsMs, disableAdvertisingIdentifier, disableIDFVCollection)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      environment,
      baseUrl,
      logLevel,
      sessionEnabled,
      minTimeBetweenSessionsMs,
      disableAdvertisingIdentifier,
      disableIDFVCollection,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AttributionOptionsDto
    return PermateAttributionApiPigeonUtils.deepEquals(this.environment, other.environment) && PermateAttributionApiPigeonUtils.deepEquals(this.baseUrl, other.baseUrl) && PermateAttributionApiPigeonUtils.deepEquals(this.logLevel, other.logLevel) && PermateAttributionApiPigeonUtils.deepEquals(this.sessionEnabled, other.sessionEnabled) && PermateAttributionApiPigeonUtils.deepEquals(this.minTimeBetweenSessionsMs, other.minTimeBetweenSessionsMs) && PermateAttributionApiPigeonUtils.deepEquals(this.disableAdvertisingIdentifier, other.disableAdvertisingIdentifier) && PermateAttributionApiPigeonUtils.deepEquals(this.disableIDFVCollection, other.disableIDFVCollection)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.environment)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.baseUrl)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.logLevel)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.sessionEnabled)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.minTimeBetweenSessionsMs)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.disableAdvertisingIdentifier)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.disableIDFVCollection)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AttributionResultDto (
  val attributed: Boolean,
  val clickId: String? = null,
  val campaignId: String? = null,
  val offerId: Long? = null,
  val partnerId: Long? = null,
  val resolvedAt: String? = null,
  val channel: String? = null,
  val isActive: Boolean? = null,
  val deferredParams: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttributionResultDto {
      val attributed = pigeonVar_list[0] as Boolean
      val clickId = pigeonVar_list[1] as String?
      val campaignId = pigeonVar_list[2] as String?
      val offerId = pigeonVar_list[3] as Long?
      val partnerId = pigeonVar_list[4] as Long?
      val resolvedAt = pigeonVar_list[5] as String?
      val channel = pigeonVar_list[6] as String?
      val isActive = pigeonVar_list[7] as Boolean?
      val deferredParams = pigeonVar_list[8] as Map<String?, String?>?
      return AttributionResultDto(attributed, clickId, campaignId, offerId, partnerId, resolvedAt, channel, isActive, deferredParams)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      attributed,
      clickId,
      campaignId,
      offerId,
      partnerId,
      resolvedAt,
      channel,
      isActive,
      deferredParams,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AttributionResultDto
    return PermateAttributionApiPigeonUtils.deepEquals(this.attributed, other.attributed) && PermateAttributionApiPigeonUtils.deepEquals(this.clickId, other.clickId) && PermateAttributionApiPigeonUtils.deepEquals(this.campaignId, other.campaignId) && PermateAttributionApiPigeonUtils.deepEquals(this.offerId, other.offerId) && PermateAttributionApiPigeonUtils.deepEquals(this.partnerId, other.partnerId) && PermateAttributionApiPigeonUtils.deepEquals(this.resolvedAt, other.resolvedAt) && PermateAttributionApiPigeonUtils.deepEquals(this.channel, other.channel) && PermateAttributionApiPigeonUtils.deepEquals(this.isActive, other.isActive) && PermateAttributionApiPigeonUtils.deepEquals(this.deferredParams, other.deferredParams)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.attributed)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.clickId)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.campaignId)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.offerId)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.partnerId)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.resolvedAt)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.channel)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.isActive)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.deferredParams)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DeepLinkResultDto (
  val campaignId: String? = null,
  val clickId: String? = null,
  val offerId: Long? = null,
  val isDeferred: Boolean,
  val rawParams: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeepLinkResultDto {
      val campaignId = pigeonVar_list[0] as String?
      val clickId = pigeonVar_list[1] as String?
      val offerId = pigeonVar_list[2] as Long?
      val isDeferred = pigeonVar_list[3] as Boolean
      val rawParams = pigeonVar_list[4] as Map<String?, String?>?
      return DeepLinkResultDto(campaignId, clickId, offerId, isDeferred, rawParams)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      campaignId,
      clickId,
      offerId,
      isDeferred,
      rawParams,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DeepLinkResultDto
    return PermateAttributionApiPigeonUtils.deepEquals(this.campaignId, other.campaignId) && PermateAttributionApiPigeonUtils.deepEquals(this.clickId, other.clickId) && PermateAttributionApiPigeonUtils.deepEquals(this.offerId, other.offerId) && PermateAttributionApiPigeonUtils.deepEquals(this.isDeferred, other.isDeferred) && PermateAttributionApiPigeonUtils.deepEquals(this.rawParams, other.rawParams)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.campaignId)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.clickId)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.offerId)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.isDeferred)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.rawParams)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RemoteConfigSnapshotDto (
  val isActive: Boolean,
  val cacheTtlSec: Long? = null,
  val fetchedAtMillis: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RemoteConfigSnapshotDto {
      val isActive = pigeonVar_list[0] as Boolean
      val cacheTtlSec = pigeonVar_list[1] as Long?
      val fetchedAtMillis = pigeonVar_list[2] as Long?
      return RemoteConfigSnapshotDto(isActive, cacheTtlSec, fetchedAtMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isActive,
      cacheTtlSec,
      fetchedAtMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RemoteConfigSnapshotDto
    return PermateAttributionApiPigeonUtils.deepEquals(this.isActive, other.isActive) && PermateAttributionApiPigeonUtils.deepEquals(this.cacheTtlSec, other.cacheTtlSec) && PermateAttributionApiPigeonUtils.deepEquals(this.fetchedAtMillis, other.fetchedAtMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.isActive)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.cacheTtlSec)
    result = 31 * result + PermateAttributionApiPigeonUtils.deepHash(this.fetchedAtMillis)
    return result
  }
}
private open class PermateAttributionApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttributionOptionsDto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttributionResultDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeepLinkResultDto.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RemoteConfigSnapshotDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AttributionOptionsDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AttributionResultDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is DeepLinkResultDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is RemoteConfigSnapshotDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PermateAttributionHostApi {
  fun getSdkVersion(): String
  fun configure(appKey: String, options: AttributionOptionsDto)
  fun start()
  fun getAttribution(): AttributionResultDto?
  fun handleDeepLink(url: String): DeepLinkResultDto?
  fun handlePushNotification(payload: Map<String?, Any?>): Boolean
  fun logEvent(name: String, params: Map<String?, Any?>?)
  fun reset()
  /**
   * Android: register FCM token for uninstall probing (`POST /push-token`).
   * iOS Flutter plugin: no-op until native ships the API.
   */
  fun updatePushToken(token: String)
  fun refreshConfig(callback: (Result<RemoteConfigSnapshotDto>) -> Unit)
  /** Host-app kill switch (native persist). Before configure: get false, set no-op. */
  fun getIsDeactivated(): Boolean
  fun setIsDeactivated(value: Boolean)
  /** iOS REQ-SDK-017 privacy toggles. Android: get false / set no-op. */
  fun getDisableAdvertisingIdentifier(): Boolean
  fun setDisableAdvertisingIdentifier(value: Boolean)
  fun getDisableIDFVCollection(): Boolean
  fun setDisableIDFVCollection(value: Boolean)
  /** Last-known IDFA, or empty when disabled / denied / Android. */
  fun getAdvertisingIdentifier(): String
  /**
   * iOS 14+: wait until ATT ≠ notDetermined (or timeout). Does not show the ATT dialog.
   * Android: no-op. Safe before configure.
   */
  fun waitForATTUserAuthorization(timeoutSeconds: Double)

  companion object {
    /** The codec used by PermateAttributionHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PermateAttributionApiPigeonCodec()
    }
    /** Sets up an instance of `PermateAttributionHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PermateAttributionHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getSdkVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSdkVersion())
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appKeyArg = args[0] as String
            val optionsArg = args[1] as AttributionOptionsDto
            val wrapped: List<Any?> = try {
              api.configure(appKeyArg, optionsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.start()
              listOf(null)
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getAttribution$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAttribution())
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.handleDeepLink$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.handleDeepLink(urlArg))
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.handlePushNotification$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val payloadArg = args[0] as Map<String?, Any?>
            val wrapped: List<Any?> = try {
              listOf(api.handlePushNotification(payloadArg))
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.logEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            val paramsArg = args[1] as Map<String?, Any?>?
            val wrapped: List<Any?> = try {
              api.logEvent(nameArg, paramsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.reset$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.reset()
              listOf(null)
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.updatePushToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.updatePushToken(tokenArg)
              listOf(null)
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.refreshConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.refreshConfig{ result: Result<RemoteConfigSnapshotDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermateAttributionApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermateAttributionApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getIsDeactivated$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getIsDeactivated())
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.setIsDeactivated$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setIsDeactivated(valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getDisableAdvertisingIdentifier$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDisableAdvertisingIdentifier())
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.setDisableAdvertisingIdentifier$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setDisableAdvertisingIdentifier(valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getDisableIDFVCollection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDisableIDFVCollection())
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.setDisableIDFVCollection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setDisableIDFVCollection(valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getAdvertisingIdentifier$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAdvertisingIdentifier())
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.waitForATTUserAuthorization$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timeoutSecondsArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.waitForATTUserAuthorization(timeoutSecondsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PermateAttributionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native → Dart callbacks (main thread on host).
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class PermateAttributionFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PermateAttributionFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PermateAttributionApiPigeonCodec()
    }
  }
  fun onAttributionSuccess(resultArg: AttributionResultDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.permate_attribution.PermateAttributionFlutterApi.onAttributionSuccess$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PermateAttributionApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * [code] is a stable wire value: `invalid_app_key`, `brand_disabled`, `http`,
   * `network_failure`, or `unknown`.
   */
  fun onAttributionFailure(codeArg: String, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.permate_attribution.PermateAttributionFlutterApi.onAttributionFailure$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PermateAttributionApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun didResolveDeepLink(resultArg: DeepLinkResultDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.permate_attribution.PermateAttributionFlutterApi.didResolveDeepLink$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PermateAttributionApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
