// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class AttributionOptionsDto {
  AttributionOptionsDto({
    required this.environment,
    this.baseUrl,
    required this.logLevel,
    required this.sessionEnabled,
    this.minTimeBetweenSessionsMs,
    required this.disableAdvertisingIdentifier,
    required this.disableIDFVCollection,
  });

  String environment;

  String? baseUrl;

  String logLevel;

  bool sessionEnabled;

  /// Null → native resolves it (Android: `/config` `session_timeout` → 30 min).
  int? minTimeBetweenSessionsMs;

  /// iOS REQ-SDK-017 — ignored on Android (no-op).
  bool disableAdvertisingIdentifier;

  /// iOS REQ-SDK-017 — ignored on Android (no-op).
  bool disableIDFVCollection;

  List<Object?> _toList() {
    return <Object?>[
      environment,
      baseUrl,
      logLevel,
      sessionEnabled,
      minTimeBetweenSessionsMs,
      disableAdvertisingIdentifier,
      disableIDFVCollection,
    ];
  }

  Object encode() {
    return _toList();  }

  static AttributionOptionsDto decode(Object result) {
    result as List<Object?>;
    return AttributionOptionsDto(
      environment: result[0]! as String,
      baseUrl: result[1] as String?,
      logLevel: result[2]! as String,
      sessionEnabled: result[3]! as bool,
      minTimeBetweenSessionsMs: result[4] as int?,
      disableAdvertisingIdentifier: result[5]! as bool,
      disableIDFVCollection: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AttributionOptionsDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(environment, other.environment) && _deepEquals(baseUrl, other.baseUrl) && _deepEquals(logLevel, other.logLevel) && _deepEquals(sessionEnabled, other.sessionEnabled) && _deepEquals(minTimeBetweenSessionsMs, other.minTimeBetweenSessionsMs) && _deepEquals(disableAdvertisingIdentifier, other.disableAdvertisingIdentifier) && _deepEquals(disableIDFVCollection, other.disableIDFVCollection);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class AttributionResultDto {
  AttributionResultDto({
    required this.attributed,
    this.clickId,
    this.campaignId,
    this.offerId,
    this.partnerId,
    this.resolvedAt,
    this.channel,
    this.isActive,
    this.deferredParams,
  });

  bool attributed;

  String? clickId;

  String? campaignId;

  int? offerId;

  int? partnerId;

  String? resolvedAt;

  String? channel;

  bool? isActive;

  Map<String?, String?>? deferredParams;

  List<Object?> _toList() {
    return <Object?>[
      attributed,
      clickId,
      campaignId,
      offerId,
      partnerId,
      resolvedAt,
      channel,
      isActive,
      deferredParams,
    ];
  }

  Object encode() {
    return _toList();  }

  static AttributionResultDto decode(Object result) {
    result as List<Object?>;
    return AttributionResultDto(
      attributed: result[0]! as bool,
      clickId: result[1] as String?,
      campaignId: result[2] as String?,
      offerId: result[3] as int?,
      partnerId: result[4] as int?,
      resolvedAt: result[5] as String?,
      channel: result[6] as String?,
      isActive: result[7] as bool?,
      deferredParams: (result[8] as Map<Object?, Object?>?)?.cast<String?, String?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AttributionResultDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(attributed, other.attributed) && _deepEquals(clickId, other.clickId) && _deepEquals(campaignId, other.campaignId) && _deepEquals(offerId, other.offerId) && _deepEquals(partnerId, other.partnerId) && _deepEquals(resolvedAt, other.resolvedAt) && _deepEquals(channel, other.channel) && _deepEquals(isActive, other.isActive) && _deepEquals(deferredParams, other.deferredParams);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class DeepLinkResultDto {
  DeepLinkResultDto({
    this.campaignId,
    this.clickId,
    this.offerId,
    required this.isDeferred,
    this.rawParams,
  });

  String? campaignId;

  String? clickId;

  int? offerId;

  bool isDeferred;

  Map<String?, String?>? rawParams;

  List<Object?> _toList() {
    return <Object?>[
      campaignId,
      clickId,
      offerId,
      isDeferred,
      rawParams,
    ];
  }

  Object encode() {
    return _toList();  }

  static DeepLinkResultDto decode(Object result) {
    result as List<Object?>;
    return DeepLinkResultDto(
      campaignId: result[0] as String?,
      clickId: result[1] as String?,
      offerId: result[2] as int?,
      isDeferred: result[3]! as bool,
      rawParams: (result[4] as Map<Object?, Object?>?)?.cast<String?, String?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeepLinkResultDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(campaignId, other.campaignId) && _deepEquals(clickId, other.clickId) && _deepEquals(offerId, other.offerId) && _deepEquals(isDeferred, other.isDeferred) && _deepEquals(rawParams, other.rawParams);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class RemoteConfigSnapshotDto {
  RemoteConfigSnapshotDto({
    required this.isActive,
    this.cacheTtlSec,
    this.fetchedAtMillis,
  });

  bool isActive;

  int? cacheTtlSec;

  int? fetchedAtMillis;

  List<Object?> _toList() {
    return <Object?>[
      isActive,
      cacheTtlSec,
      fetchedAtMillis,
    ];
  }

  Object encode() {
    return _toList();  }

  static RemoteConfigSnapshotDto decode(Object result) {
    result as List<Object?>;
    return RemoteConfigSnapshotDto(
      isActive: result[0]! as bool,
      cacheTtlSec: result[1] as int?,
      fetchedAtMillis: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RemoteConfigSnapshotDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isActive, other.isActive) && _deepEquals(cacheTtlSec, other.cacheTtlSec) && _deepEquals(fetchedAtMillis, other.fetchedAtMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AttributionOptionsDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is AttributionResultDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is DeepLinkResultDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is RemoteConfigSnapshotDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return AttributionOptionsDto.decode(readValue(buffer)!);
      case 130:
        return AttributionResultDto.decode(readValue(buffer)!);
      case 131:
        return DeepLinkResultDto.decode(readValue(buffer)!);
      case 132:
        return RemoteConfigSnapshotDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PermateAttributionHostApi {
  /// Constructor for [PermateAttributionHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PermateAttributionHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<String> getSdkVersion() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getSdkVersion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<void> configure(String appKey, AttributionOptionsDto options) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.configure$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[appKey, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> start() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<AttributionResultDto?> getAttribution() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getAttribution$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as AttributionResultDto?;
  }

  Future<DeepLinkResultDto?> handleDeepLink(String url) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.handleDeepLink$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[url]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as DeepLinkResultDto?;
  }

  Future<bool> handlePushNotification(Map<String?, Object?> payload) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.handlePushNotification$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[payload]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> logEvent(String name, Map<String?, Object?>? params) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.logEvent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[name, params]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> reset() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.reset$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Android: register FCM token for uninstall probing (`POST /push-token`).
  /// iOS Flutter plugin: no-op until native ships the API.
  Future<void> updatePushToken(String token) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.updatePushToken$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[token]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<RemoteConfigSnapshotDto> refreshConfig() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.refreshConfig$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as RemoteConfigSnapshotDto;
  }

  /// Host-app kill switch (native persist). Before configure: get false, set no-op.
  Future<bool> getIsDeactivated() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getIsDeactivated$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> setIsDeactivated(bool value) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.setIsDeactivated$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// iOS REQ-SDK-017 privacy toggles. Android: get false / set no-op.
  Future<bool> getDisableAdvertisingIdentifier() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getDisableAdvertisingIdentifier$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> setDisableAdvertisingIdentifier(bool value) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.setDisableAdvertisingIdentifier$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> getDisableIDFVCollection() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getDisableIDFVCollection$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> setDisableIDFVCollection(bool value) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.setDisableIDFVCollection$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Last-known IDFA, or empty when disabled / denied / Android.
  Future<String> getAdvertisingIdentifier() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getAdvertisingIdentifier$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  /// iOS 14+: wait until ATT ≠ notDetermined (or timeout). Does not show the ATT dialog.
  /// Android: no-op. Safe before configure.
  Future<void> waitForATTUserAuthorization(double timeoutSeconds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.waitForATTUserAuthorization$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[timeoutSeconds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Native → Dart callbacks (main thread on host).
abstract class PermateAttributionFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onAttributionSuccess(AttributionResultDto result);

  /// [code] is a stable wire value: `invalid_app_key`, `brand_disabled`, `http`,
  /// `network_failure`, or `unknown`.
  void onAttributionFailure(String code, String message);

  void didResolveDeepLink(DeepLinkResultDto result);

  static void setUp(PermateAttributionFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.permate_attribution.PermateAttributionFlutterApi.onAttributionSuccess$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AttributionResultDto arg_result = args[0]! as AttributionResultDto;
          try {
            api.onAttributionSuccess(arg_result);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.permate_attribution.PermateAttributionFlutterApi.onAttributionFailure$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_code = args[0]! as String;
          final String arg_message = args[1]! as String;
          try {
            api.onAttributionFailure(arg_code, arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.permate_attribution.PermateAttributionFlutterApi.didResolveDeepLink$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final DeepLinkResultDto arg_result = args[0]! as DeepLinkResultDto;
          try {
            api.didResolveDeepLink(arg_result);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
