// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsPermateAttributionApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashPermateAttributionApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsPermateAttributionApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsPermateAttributionApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsPermateAttributionApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsPermateAttributionApi(lhsKey, rhsKey) {
          if deepEqualsPermateAttributionApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsPermateAttributionApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashPermateAttributionApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashPermateAttributionApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashPermateAttributionApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashPermateAttributionApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashPermateAttributionApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashPermateAttributionApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct AttributionOptionsDto: Hashable {
  var environment: String
  var baseUrl: String? = nil
  var logLevel: String
  var sessionEnabled: Bool
  /// Null → native resolves it (Android: `/config` `session_timeout` → 30 min).
  var minTimeBetweenSessionsMs: Int64? = nil
  /// iOS REQ-SDK-017 — ignored on Android (no-op).
  var disableAdvertisingIdentifier: Bool
  /// iOS REQ-SDK-017 — ignored on Android (no-op).
  var disableIDFVCollection: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AttributionOptionsDto? {
    let environment = pigeonVar_list[0] as! String
    let baseUrl: String? = nilOrValue(pigeonVar_list[1])
    let logLevel = pigeonVar_list[2] as! String
    let sessionEnabled = pigeonVar_list[3] as! Bool
    let minTimeBetweenSessionsMs: Int64? = nilOrValue(pigeonVar_list[4])
    let disableAdvertisingIdentifier = pigeonVar_list[5] as! Bool
    let disableIDFVCollection = pigeonVar_list[6] as! Bool

    return AttributionOptionsDto(
      environment: environment,
      baseUrl: baseUrl,
      logLevel: logLevel,
      sessionEnabled: sessionEnabled,
      minTimeBetweenSessionsMs: minTimeBetweenSessionsMs,
      disableAdvertisingIdentifier: disableAdvertisingIdentifier,
      disableIDFVCollection: disableIDFVCollection
    )
  }
  func toList() -> [Any?] {
    return [
      environment,
      baseUrl,
      logLevel,
      sessionEnabled,
      minTimeBetweenSessionsMs,
      disableAdvertisingIdentifier,
      disableIDFVCollection,
    ]
  }
  static func == (lhs: AttributionOptionsDto, rhs: AttributionOptionsDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPermateAttributionApi(lhs.environment, rhs.environment) && deepEqualsPermateAttributionApi(lhs.baseUrl, rhs.baseUrl) && deepEqualsPermateAttributionApi(lhs.logLevel, rhs.logLevel) && deepEqualsPermateAttributionApi(lhs.sessionEnabled, rhs.sessionEnabled) && deepEqualsPermateAttributionApi(lhs.minTimeBetweenSessionsMs, rhs.minTimeBetweenSessionsMs) && deepEqualsPermateAttributionApi(lhs.disableAdvertisingIdentifier, rhs.disableAdvertisingIdentifier) && deepEqualsPermateAttributionApi(lhs.disableIDFVCollection, rhs.disableIDFVCollection)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AttributionOptionsDto")
    deepHashPermateAttributionApi(value: environment, hasher: &hasher)
    deepHashPermateAttributionApi(value: baseUrl, hasher: &hasher)
    deepHashPermateAttributionApi(value: logLevel, hasher: &hasher)
    deepHashPermateAttributionApi(value: sessionEnabled, hasher: &hasher)
    deepHashPermateAttributionApi(value: minTimeBetweenSessionsMs, hasher: &hasher)
    deepHashPermateAttributionApi(value: disableAdvertisingIdentifier, hasher: &hasher)
    deepHashPermateAttributionApi(value: disableIDFVCollection, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AttributionResultDto: Hashable {
  var attributed: Bool
  var clickId: String? = nil
  var campaignId: String? = nil
  var offerId: Int64? = nil
  var partnerId: Int64? = nil
  var resolvedAt: String? = nil
  var channel: String? = nil
  var isActive: Bool? = nil
  var deferredParams: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AttributionResultDto? {
    let attributed = pigeonVar_list[0] as! Bool
    let clickId: String? = nilOrValue(pigeonVar_list[1])
    let campaignId: String? = nilOrValue(pigeonVar_list[2])
    let offerId: Int64? = nilOrValue(pigeonVar_list[3])
    let partnerId: Int64? = nilOrValue(pigeonVar_list[4])
    let resolvedAt: String? = nilOrValue(pigeonVar_list[5])
    let channel: String? = nilOrValue(pigeonVar_list[6])
    let isActive: Bool? = nilOrValue(pigeonVar_list[7])
    let deferredParams: [String?: String?]? = nilOrValue(pigeonVar_list[8])

    return AttributionResultDto(
      attributed: attributed,
      clickId: clickId,
      campaignId: campaignId,
      offerId: offerId,
      partnerId: partnerId,
      resolvedAt: resolvedAt,
      channel: channel,
      isActive: isActive,
      deferredParams: deferredParams
    )
  }
  func toList() -> [Any?] {
    return [
      attributed,
      clickId,
      campaignId,
      offerId,
      partnerId,
      resolvedAt,
      channel,
      isActive,
      deferredParams,
    ]
  }
  static func == (lhs: AttributionResultDto, rhs: AttributionResultDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPermateAttributionApi(lhs.attributed, rhs.attributed) && deepEqualsPermateAttributionApi(lhs.clickId, rhs.clickId) && deepEqualsPermateAttributionApi(lhs.campaignId, rhs.campaignId) && deepEqualsPermateAttributionApi(lhs.offerId, rhs.offerId) && deepEqualsPermateAttributionApi(lhs.partnerId, rhs.partnerId) && deepEqualsPermateAttributionApi(lhs.resolvedAt, rhs.resolvedAt) && deepEqualsPermateAttributionApi(lhs.channel, rhs.channel) && deepEqualsPermateAttributionApi(lhs.isActive, rhs.isActive) && deepEqualsPermateAttributionApi(lhs.deferredParams, rhs.deferredParams)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AttributionResultDto")
    deepHashPermateAttributionApi(value: attributed, hasher: &hasher)
    deepHashPermateAttributionApi(value: clickId, hasher: &hasher)
    deepHashPermateAttributionApi(value: campaignId, hasher: &hasher)
    deepHashPermateAttributionApi(value: offerId, hasher: &hasher)
    deepHashPermateAttributionApi(value: partnerId, hasher: &hasher)
    deepHashPermateAttributionApi(value: resolvedAt, hasher: &hasher)
    deepHashPermateAttributionApi(value: channel, hasher: &hasher)
    deepHashPermateAttributionApi(value: isActive, hasher: &hasher)
    deepHashPermateAttributionApi(value: deferredParams, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DeepLinkResultDto: Hashable {
  var campaignId: String? = nil
  var clickId: String? = nil
  var offerId: Int64? = nil
  var isDeferred: Bool
  var rawParams: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeepLinkResultDto? {
    let campaignId: String? = nilOrValue(pigeonVar_list[0])
    let clickId: String? = nilOrValue(pigeonVar_list[1])
    let offerId: Int64? = nilOrValue(pigeonVar_list[2])
    let isDeferred = pigeonVar_list[3] as! Bool
    let rawParams: [String?: String?]? = nilOrValue(pigeonVar_list[4])

    return DeepLinkResultDto(
      campaignId: campaignId,
      clickId: clickId,
      offerId: offerId,
      isDeferred: isDeferred,
      rawParams: rawParams
    )
  }
  func toList() -> [Any?] {
    return [
      campaignId,
      clickId,
      offerId,
      isDeferred,
      rawParams,
    ]
  }
  static func == (lhs: DeepLinkResultDto, rhs: DeepLinkResultDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPermateAttributionApi(lhs.campaignId, rhs.campaignId) && deepEqualsPermateAttributionApi(lhs.clickId, rhs.clickId) && deepEqualsPermateAttributionApi(lhs.offerId, rhs.offerId) && deepEqualsPermateAttributionApi(lhs.isDeferred, rhs.isDeferred) && deepEqualsPermateAttributionApi(lhs.rawParams, rhs.rawParams)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DeepLinkResultDto")
    deepHashPermateAttributionApi(value: campaignId, hasher: &hasher)
    deepHashPermateAttributionApi(value: clickId, hasher: &hasher)
    deepHashPermateAttributionApi(value: offerId, hasher: &hasher)
    deepHashPermateAttributionApi(value: isDeferred, hasher: &hasher)
    deepHashPermateAttributionApi(value: rawParams, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RemoteConfigSnapshotDto: Hashable {
  var isActive: Bool
  var cacheTtlSec: Int64? = nil
  var fetchedAtMillis: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RemoteConfigSnapshotDto? {
    let isActive = pigeonVar_list[0] as! Bool
    let cacheTtlSec: Int64? = nilOrValue(pigeonVar_list[1])
    let fetchedAtMillis: Int64? = nilOrValue(pigeonVar_list[2])

    return RemoteConfigSnapshotDto(
      isActive: isActive,
      cacheTtlSec: cacheTtlSec,
      fetchedAtMillis: fetchedAtMillis
    )
  }
  func toList() -> [Any?] {
    return [
      isActive,
      cacheTtlSec,
      fetchedAtMillis,
    ]
  }
  static func == (lhs: RemoteConfigSnapshotDto, rhs: RemoteConfigSnapshotDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPermateAttributionApi(lhs.isActive, rhs.isActive) && deepEqualsPermateAttributionApi(lhs.cacheTtlSec, rhs.cacheTtlSec) && deepEqualsPermateAttributionApi(lhs.fetchedAtMillis, rhs.fetchedAtMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RemoteConfigSnapshotDto")
    deepHashPermateAttributionApi(value: isActive, hasher: &hasher)
    deepHashPermateAttributionApi(value: cacheTtlSec, hasher: &hasher)
    deepHashPermateAttributionApi(value: fetchedAtMillis, hasher: &hasher)
  }
}

private class PermateAttributionApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AttributionOptionsDto.fromList(self.readValue() as! [Any?])
    case 130:
      return AttributionResultDto.fromList(self.readValue() as! [Any?])
    case 131:
      return DeepLinkResultDto.fromList(self.readValue() as! [Any?])
    case 132:
      return RemoteConfigSnapshotDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PermateAttributionApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AttributionOptionsDto {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AttributionResultDto {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? DeepLinkResultDto {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? RemoteConfigSnapshotDto {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PermateAttributionApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PermateAttributionApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PermateAttributionApiPigeonCodecWriter(data: data)
  }
}

class PermateAttributionApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PermateAttributionApiPigeonCodec(readerWriter: PermateAttributionApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PermateAttributionHostApi {
  func getSdkVersion() throws -> String
  func configure(appKey: String, options: AttributionOptionsDto) throws
  func start() throws
  func getAttribution() throws -> AttributionResultDto?
  func handleDeepLink(url: String) throws -> DeepLinkResultDto?
  func handlePushNotification(payload: [String?: Any?]) throws -> Bool
  func logEvent(name: String, params: [String?: Any?]?) throws
  func reset() throws
  /// Android: register FCM token for uninstall probing (`POST /push-token`).
  /// iOS Flutter plugin: no-op until native ships the API.
  func updatePushToken(token: String) throws
  func refreshConfig(completion: @escaping (Result<RemoteConfigSnapshotDto, Error>) -> Void)
  /// Host-app kill switch (native persist). Before configure: get false, set no-op.
  func getIsDeactivated() throws -> Bool
  func setIsDeactivated(value: Bool) throws
  /// iOS REQ-SDK-017 privacy toggles. Android: get false / set no-op.
  func getDisableAdvertisingIdentifier() throws -> Bool
  func setDisableAdvertisingIdentifier(value: Bool) throws
  func getDisableIDFVCollection() throws -> Bool
  func setDisableIDFVCollection(value: Bool) throws
  /// Last-known IDFA, or empty when disabled / denied / Android.
  func getAdvertisingIdentifier() throws -> String
  /// iOS 14+: wait until ATT ≠ notDetermined (or timeout). Does not show the ATT dialog.
  /// Android: no-op. Safe before configure.
  func waitForATTUserAuthorization(timeoutSeconds: Double) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PermateAttributionHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PermateAttributionApiPigeonCodec.shared }
  /// Sets up an instance of `PermateAttributionHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PermateAttributionHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getSdkVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getSdkVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSdkVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getSdkVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSdkVersionChannel.setMessageHandler(nil)
    }
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appKeyArg = args[0] as! String
        let optionsArg = args[1] as! AttributionOptionsDto
        do {
          try api.configure(appKey: appKeyArg, options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { _, reply in
        do {
          try api.start()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let getAttributionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getAttribution\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAttributionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAttribution()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAttributionChannel.setMessageHandler(nil)
    }
    let handleDeepLinkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.handleDeepLink\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handleDeepLinkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        do {
          let result = try api.handleDeepLink(url: urlArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      handleDeepLinkChannel.setMessageHandler(nil)
    }
    let handlePushNotificationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.handlePushNotification\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handlePushNotificationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadArg = args[0] as! [String?: Any?]
        do {
          let result = try api.handlePushNotification(payload: payloadArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      handlePushNotificationChannel.setMessageHandler(nil)
    }
    let logEventChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.logEvent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      logEventChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        let paramsArg: [String?: Any?]? = nilOrValue(args[1])
        do {
          try api.logEvent(name: nameArg, params: paramsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      logEventChannel.setMessageHandler(nil)
    }
    let resetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.reset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetChannel.setMessageHandler { _, reply in
        do {
          try api.reset()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resetChannel.setMessageHandler(nil)
    }
    /// Android: register FCM token for uninstall probing (`POST /push-token`).
    /// iOS Flutter plugin: no-op until native ships the API.
    let updatePushTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.updatePushToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePushTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        do {
          try api.updatePushToken(token: tokenArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updatePushTokenChannel.setMessageHandler(nil)
    }
    let refreshConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.refreshConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      refreshConfigChannel.setMessageHandler { _, reply in
        api.refreshConfig { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      refreshConfigChannel.setMessageHandler(nil)
    }
    /// Host-app kill switch (native persist). Before configure: get false, set no-op.
    let getIsDeactivatedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getIsDeactivated\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getIsDeactivatedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getIsDeactivated()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getIsDeactivatedChannel.setMessageHandler(nil)
    }
    let setIsDeactivatedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.setIsDeactivated\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setIsDeactivatedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.setIsDeactivated(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setIsDeactivatedChannel.setMessageHandler(nil)
    }
    /// iOS REQ-SDK-017 privacy toggles. Android: get false / set no-op.
    let getDisableAdvertisingIdentifierChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getDisableAdvertisingIdentifier\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDisableAdvertisingIdentifierChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDisableAdvertisingIdentifier()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDisableAdvertisingIdentifierChannel.setMessageHandler(nil)
    }
    let setDisableAdvertisingIdentifierChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.setDisableAdvertisingIdentifier\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDisableAdvertisingIdentifierChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.setDisableAdvertisingIdentifier(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setDisableAdvertisingIdentifierChannel.setMessageHandler(nil)
    }
    let getDisableIDFVCollectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getDisableIDFVCollection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDisableIDFVCollectionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDisableIDFVCollection()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDisableIDFVCollectionChannel.setMessageHandler(nil)
    }
    let setDisableIDFVCollectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.setDisableIDFVCollection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDisableIDFVCollectionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.setDisableIDFVCollection(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setDisableIDFVCollectionChannel.setMessageHandler(nil)
    }
    /// Last-known IDFA, or empty when disabled / denied / Android.
    let getAdvertisingIdentifierChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.getAdvertisingIdentifier\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAdvertisingIdentifierChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAdvertisingIdentifier()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAdvertisingIdentifierChannel.setMessageHandler(nil)
    }
    /// iOS 14+: wait until ATT ≠ notDetermined (or timeout). Does not show the ATT dialog.
    /// Android: no-op. Safe before configure.
    let waitForATTUserAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permate_attribution.PermateAttributionHostApi.waitForATTUserAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      waitForATTUserAuthorizationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timeoutSecondsArg = args[0] as! Double
        do {
          try api.waitForATTUserAuthorization(timeoutSeconds: timeoutSecondsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      waitForATTUserAuthorizationChannel.setMessageHandler(nil)
    }
  }
}
/// Native → Dart callbacks (main thread on host).
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PermateAttributionFlutterApiProtocol {
  func onAttributionSuccess(result resultArg: AttributionResultDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// [code] is a stable wire value: `invalid_app_key`, `brand_disabled`, `http`,
  /// `network_failure`, or `unknown`.
  func onAttributionFailure(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func didResolveDeepLink(result resultArg: DeepLinkResultDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class PermateAttributionFlutterApi: PermateAttributionFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PermateAttributionApiPigeonCodec {
    return PermateAttributionApiPigeonCodec.shared
  }
  func onAttributionSuccess(result resultArg: AttributionResultDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.permate_attribution.PermateAttributionFlutterApi.onAttributionSuccess\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// [code] is a stable wire value: `invalid_app_key`, `brand_disabled`, `http`,
  /// `network_failure`, or `unknown`.
  func onAttributionFailure(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.permate_attribution.PermateAttributionFlutterApi.onAttributionFailure\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([codeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func didResolveDeepLink(result resultArg: DeepLinkResultDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.permate_attribution.PermateAttributionFlutterApi.didResolveDeepLink\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
